[project]
name = 'agassi'
description = 'Demonstrates a basic fungible token that conforms to agassi'
authors = []
telemetry = true
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard'

[contracts.agassi]
path = 'contracts/agassi.clar'
clarity_version = 4
epoch = "latest"

[contracts.defi]
path = 'contracts/extern/defi.clar'
clarity_version = 4
epoch = "latest"

